name: Check Links

on:
  workflow_dispatch: {}
  schedule:
    - cron: "00 18 * * *"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Download earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/'${version}'/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
        env:
          version: v0.7.23

      - name: Check for broken links
        run: earthly --ci +lint-lychee
        env:
          EARTHLY_SECRETS: ${{ secrets.EARTHLY_SECRETS }}

      # FIXME: Move logic to earthly.
      - name: Create issue from lychee output file
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
